### ISSUE TITLE
please, could you help me?

### ISSUE THREAD

**Issue by joaquinpm** [lukaszbinden/rsi_tradingview#1]
Hi Lukas, how are you?
First at all, I'm very nooby in Python but I'm a trader. I've tryed to make RSI formula in Excel but the result is wrong because Trading View use a RMA,
So how I do to import the base date of close prices to the IDLE, if for example I have those in Excel?
What does "import pandas as pd" mean? and...What does "import numpy as np" mean?

Please, could you help me to use RSI programme?

Many thanks in advance.
King regards.
Joaquin

**Comment by machine-trading** [comment]
Dear Joaquin, you can get in touch with me through lz8268 at gmail com

**Comment by lukaszbinden** [comment]
Dear Joaquin, you can get in touch with me through lz8268 at gmail com
