### ISSUE TITLE
Result do not match with Tradingview.

### ISSUE THREAD

**Issue by abiurrunc** [lukaszbinden/rsi_tradingview#3]
Hello Lukas.

Fisrt of all, thanks for share the function.

I'm comparing the RSI function result with tradingview result they don't match.
I'm trying to get RSI14 and RSI2 fron the next values:
            data = [
                {"close": 55938.97},
                {"close": 55976.78},
                {"close": 56015.49},
                {"close": 56062.53},
                {"close": 56022.07},
                {"close": 55945.20},
                {"close": 55930.00},
                {"close": 55901.06},
                {"close": 55912.92},
                {"close": 55869.55},
                {"close": 55846.52},
                {"close": 55821.63},
                {"close": 55905.33},
                {"close": 55885.20},
                {"close": 56042.08},
                {"close": 56094.94},
                {"close": 56010.04}]
Them come from Tradingview and Binance I got them manueally from 7 apr 22:16 to  7 apr 22:32
The tradingview and Binance RSI results are:
     RSI 14: 51.34
     RSI 2 : 44.35

From the function I get:
     RSI 14: 56.21
     RSI 2 : 44.35 This is right.

Why I can not get both result as Tradingview or Binance?
Many Thanks and have a nice weekend.
Angel.

**Comment by lukaszbinden** [comment]
Hi Angel

Have a look at the formula for RSI. It is defined in terms of its previous values. So you need to use enough historical data (say length of 200) to make sure the current RSI value will converge to the actual value that you see in TradingView.
If you only use a short history it will deviate a lot from TradingView.

Binance I haven't checked if they use the same formula as TradingView.

Cheers, 
Lukas

**Comment by abiurrunc** [comment]
Many Thanks Lukas, you're genius.
